name: Image Builder Build CI

on:
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the image builder
      run: docker build .
